services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=tempo_db'
      - 'POSTGRES_USER=tempo_user'
      - 'POSTGRES_PASSWORD=tempo_pass'
      - 'POSTGRES_INITDB_ARGS=--encoding=UTF-8'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Initialisation optionnelle
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U tempo_user -d tempo_db']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://postgres:5432/tempo_db -user=tempo_user -password=tempo_pass -connectRetries=60 -baselineOnMigrate=true -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./src/main/resources/db/migration/postgresql:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: dockerfile.dev
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/tempo_db
      - DB_USERNAME=tempo_user
      - DB_PASSWORD=tempo_pass
      - APP_SECRET_KEY=secretazertyuiopqsdfghjklmwxcvbnazertyuiopqsdfghjklmwxcvbn
      - JAVA_OPTS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=postgresql
      - SPRING_FLYWAY_ENABLED=false
      # Configuration DevTools
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
      - SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=1000
      - SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=400
    ports:
      - '8080:8080'
      - '35729:35729' # Port pour LiveReload
    volumes:
      # Montage du code source pour le hot reload
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      # Cache Maven pour éviter de retélécharger les dépendances
      - maven-cache:/root/.m2
    depends_on:
      flyway:
        condition: service_completed_successfully
    networks:
      - app-network

volumes:
  postgres_data:
  maven-cache:

networks:
  app-network:
    driver: bridge
