services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
      - 'MYSQL_ROOT_HOST=%'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/mydatabase
      - DB_USERNAME=myuser
      - DB_PASSWORD=secret
      - APP_SECRET_KEY=secretazertyuiopqsdfghjklmwxcvbnazertyuiop
    ports:
      - '8080:8080'
    depends_on:
      - mysql

volumes:
  db_data:
