services:
  mysql:
    image: 'mysql:latest'
    # image: 'arm64v8/mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
      - 'MYSQL_ROOT_HOST=%'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'myuser',
          '--password=secret',
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  flyway-baseline:
    image: flyway/flyway:latest
    command: -url=jdbc:mysql://mysql:3306/mydatabase -user=myuser -password=secret -connectRetries=60 baseline
    volumes:
      - ./src/main/resources/db/migration:/flyway/migrations
    profiles:
      - baseline
    depends_on:
      mysql:
        condition: service_healthy

  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:mysql://mysql:3306/mydatabase -user=myuser -password=secret -connectRetries=60 -baselineOnMigrate=true -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  api:
    build: .
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/mydatabase
      - DB_USERNAME=myuser
      - DB_PASSWORD=secret
      - APP_SECRET_KEY=secretazertyuiopqsdfghjklmwxcvbnazertyuiop
      - JAVA_OPTS=-Xmx512m -Xms256m
      # Configuration Flyway désactivée car gérée par le service flyway
      - SPRING_FLYWAY_ENABLED=false
    ports:
      - '8080:8080'
    depends_on:
      flyway:
        condition: service_completed_successfully
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
